CREATE TABLE participants (
SUBJ_ID VARCHAR(100) PRIMARY KEY,
TRT VARCHAR(100),
AGE DECIMAL(10,1),
SEX VARCHAR(25),
RACE VARCHAR(50)
);

CREATE TABLE aesae (
AE_ID INT PRIMARY KEY,
SUBJ_ID VARCHAR(100),
AEDECOD VARCHAR(100),
AESEV VARCHAR(50),
AESER VARCHAR(10),
FOREIGN KEY (SUBJ_ID) REFERENCES participants(SUBJ_ID)
);